In [13]:
import pandas as pd

df_general = pd.read_csv("../data/2_processed/questions_generals_reranked.csv")

df_specifics = pd.read_csv("../data/2_processed/questions_specific_reranked.csv")
df_general['specific'] = 0
df_specifics['specific'] = 1

In [5]:
df_specifics.__len__()

346

In [7]:
df_general.__len__()

344

In [16]:
df_resultado = pd.concat([df_general, df_specifics.sample(n=156)], ignore_index=True)
df_resultado

,Unnamed: 0,question,keyword,doc_id_1,abstract_1,doc_id_2,abstract_2,doc_id_3,abstract_3,doc_id_4,...,rrf_res,rrf_mrr,union_docs,union_res,max_score,min_score,specific,doc_id,abstract,score
0,1.0,"What are the emerging challenges, technologica...",research,2311.0,While extensive guidance exists for ensuring t...,747.0,The field of weather and climate science is at...,2706.0,With the rapid amassing of spatial-temporal (S...,3511.0,...,0.8,1.0,"[""2706"", ""747"", ""5204"", ""74"", ""3028"", ""986"", ""...",0.8,0.207169,-0.142616,0,NaN,NaN,NaN
1,4.0,How are complex network representations and an...,network,6874.0,We study the kinematics of nonlinear resonance...,2903.0,Atmospheric simulations for urban cities can b...,6719.0,We construct a network from climate records of...,6236.0,...,0.6,1.0,"[""3932"", ""7570"", ""6019"", ""7286"", ""6236"", ""6678...",0.6,0.406671,-0.172737,0,NaN,NaN,NaN
2,5.0,What methods and mechanisms have been identifi...,circulation,1330.0,Recent field campaigns have consistently docum...,1235.0,The global ocean meridional overturning circul...,1773.0,There is a reasonable possibility that the pre...,7387.0,...,0.4,1.0,"[""1235"", ""7256"", ""2651"", ""3655"", ""8333"", ""6355...",0.4,0.368187,-0.037046,0,NaN,NaN,NaN
3,7.0,"What factors, mechanisms, and potential trade-...",greenhouse,2990.0,Along with the accumulation of atmospheric car...,3828.0,"Some have suggested solar geoengineering, cool...",5082.0,As global greenhouse gas emissions continue to...,3591.0,...,0.8,1.0,"[""7951"", ""2990"", ""7693"", ""2584"", ""3434"", ""3057...",0.8,0.422982,-0.141840,0,NaN,NaN,NaN
4,8.0,What computational modeling techniques and sim...,simulation,4737.0,Rocket exhaust plumes have been observed to ca...,490.0,The N.E.O.N.-Bridge is a capstone project bein...,6081.0,Quasilinear theory is often utilized to approx...,22.0,...,0.0,0.0,"[""7075"", ""3629"", ""7832"", ""7837"", ""3260"", ""4008...",0.2,0.216290,-0.096269,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,NaN,What is the resolution of the sea ice forecast...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1637.0,Variation of Arctic sea ice has significant im...,0.798308
496,NaN,What decay of turbulent spectra are the rapid ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,4499.0,We use an Autoregressive (AR) approach combine...,0.724219
497,NaN,What appears to be the relationship between th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,6798.0,Our previous results on the connection between...,0.851507
498,NaN,What is the primary driver of the gradient of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1247.0,Photo-evaporation shapes the observed radii of...,0.725666
499,NaN,What happens to the correlation between the EN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,3969.0,We revisit long-standing controversies regardi...,0.837872

In [19]:
cols = ['doc_id_1','doc_id_2', 'doc_id_3', 'doc_id_4', 'doc_id_5', 'doc_id']
df_resultado['ids_docs'] = df_resultado[cols].apply(lambda x: x.dropna().tolist(), axis=1)
df_resultado

,Unnamed: 0,question,keyword,doc_id_1,abstract_1,doc_id_2,abstract_2,doc_id_3,abstract_3,doc_id_4,...,rrf_mrr,union_docs,union_res,max_score,min_score,specific,doc_id,abstract,score,ids_docs
0,1.0,"What are the emerging challenges, technologica...",research,2311.0,While extensive guidance exists for ensuring t...,747.0,The field of weather and climate science is at...,2706.0,With the rapid amassing of spatial-temporal (S...,3511.0,...,1.0,"[""2706"", ""747"", ""5204"", ""74"", ""3028"", ""986"", ""...",0.8,0.207169,-0.142616,0,NaN,NaN,NaN,"[2311.0, 747.0, 2706.0, 3511.0, 2545.0]"
1,4.0,How are complex network representations and an...,network,6874.0,We study the kinematics of nonlinear resonance...,2903.0,Atmospheric simulations for urban cities can b...,6719.0,We construct a network from climate records of...,6236.0,...,1.0,"[""3932"", ""7570"", ""6019"", ""7286"", ""6236"", ""6678...",0.6,0.406671,-0.172737,0,NaN,NaN,NaN,"[6874.0, 2903.0, 6719.0, 6236.0, 3932.0]"
2,5.0,What methods and mechanisms have been identifi...,circulation,1330.0,Recent field campaigns have consistently docum...,1235.0,The global ocean meridional overturning circul...,1773.0,There is a reasonable possibility that the pre...,7387.0,...,1.0,"[""1235"", ""7256"", ""2651"", ""3655"", ""8333"", ""6355...",0.4,0.368187,-0.037046,0,NaN,NaN,NaN,"[1330.0, 1235.0, 1773.0, 7387.0, 2651.0]"
3,7.0,"What factors, mechanisms, and potential trade-...",greenhouse,2990.0,Along with the accumulation of atmospheric car...,3828.0,"Some have suggested solar geoengineering, cool...",5082.0,As global greenhouse gas emissions continue to...,3591.0,...,1.0,"[""7951"", ""2990"", ""7693"", ""2584"", ""3434"", ""3057...",0.8,0.422982,-0.141840,0,NaN,NaN,NaN,"[2990.0, 3828.0, 5082.0, 3591.0, 7951.0]"
4,8.0,What computational modeling techniques and sim...,simulation,4737.0,Rocket exhaust plumes have been observed to ca...,490.0,The N.E.O.N.-Bridge is a capstone project bein...,6081.0,Quasilinear theory is often utilized to approx...,22.0,...,0.0,"[""7075"", ""3629"", ""7832"", ""7837"", ""3260"", ""4008...",0.2,0.216290,-0.096269,0,NaN,NaN,NaN,"[4737.0, 490.0, 6081.0, 22.0, 6974.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,NaN,What is the resolution of the sea ice forecast...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,1637.0,Variation of Arctic sea ice has significant im...,0.798308,[1637.0]
496,NaN,What decay of turbulent spectra are the rapid ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,4499.0,We use an Autoregressive (AR) approach combine...,0.724219,[4499.0]
497,NaN,What appears to be the relationship between th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,6798.0,Our previous results on the connection between...,0.851507,[6798.0]
498,NaN,What is the primary driver of the gradient of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,1247.0,Photo-evaporation shapes the observed radii of...,0.725666,[1247.0]
499,NaN,What happens to the correlation between the EN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,3969.0,We revisit long-standing controversies regardi...,0.837872,[3969.0]

In [25]:
df_resultado[['ids_docs', 'question']]

df_resultado.to_csv("../data/2_processed/questions_finals.csv")
df_resultado[['ids_docs', 'question', 'specific']].to_csv('../data/2_processed/question_finals(res).csv')